volumes:
  minio_data:

services:
  log_archiver:
    image: albertsabirzianov/logs_archiver:latest
    volumes:
      - ${LOGS_DIR}:/logs
    environment:
      - S3_HOST=${S3_HOST}
      - S3_PORT=${S3_PORT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      #- LOG_FILE_EXTENSIONS:${LOG_FILE_EXTENSIONS}
      - MAX_LOG_FILE_SIZE_IN_BYTES=${MAX_LOG_FILE_SIZE_IN_BYTES}
      - TIME_TO_LIVE_LOG_ARCHIVES_IN_SECONDS=${TIME_TO_LIVE_LOG_ARCHIVES_IN_SECONDS}

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ACCESS_KEY=${S3_ACCESS_KEY}
      - MINIO_SECRET_KEY=${S3_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data


